version: '3.8'

services:
  gym_manager_backend:
    build:
      context: ./.docker/backend
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    container_name: gym_manager_backend
    restart: unless-stopped
    volumes:
      - ./src:/var/www/gym_manager/
      - ./.docker/backend/apache-default.conf:/etc/apache2/sites-available/000-default.conf
    working_dir: /var/www/gym_manager/
    networks:
      - gym_manager_network

# docker-compose down -v --rmi all --remove-orphans
